[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["feedreaper", "lazysummary", "lazycanvas", "lazysocials", "lazycommon", "lazyvideo"]

[project]
name = "lazycontent"
version = "0.0.0"
